services:
  postgres:
    image: postgres:15
    container_name: dvdrental-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dvdrental-network

  api:
    build: ./api
    container_name: dvdrental-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=dvdrental
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dvdrental-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  dvdrental-network:
    driver: bridge